// Encrypts the "under submission" paper list into assets/js/private-drafts.data.js.
//
// Usage:
//   DRAFTS_PASSPHRASE='your secret' node src/encrypt-drafts.mjs
//   node src/encrypt-drafts.mjs            # prompts for the passphrase (muted)
//
// Reads plaintext from resources/drafts.private.html (gitignored — never committed).
// Writes assets/js/private-drafts.data.js (committed — contains only ciphertext).
//
// Uses the Web Crypto API — the *same* primitives the browser uses to decrypt — so
// encrypt and decrypt are guaranteed compatible. The passphrase is never written to
// disk; it comes from the env var or the interactive prompt and is used only in memory.

import { webcrypto } from 'node:crypto';
import readline from 'node:readline';
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const { subtle } = webcrypto;
const ITERATIONS = 150000; // PBKDF2 iterations — must match assets/js/private-drafts.js
const SALT_LEN = 16;
const IV_LEN = 12;

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(__dirname, '..');
const PLAINTEXT_PATH = path.join(ROOT, 'resources', 'drafts.private.html');
const OUTPUT_PATH = path.join(ROOT, 'assets', 'js', 'private-drafts.data.js');

function toB64(bytes) {
  return Buffer.from(bytes).toString('base64');
}

function readPassphrase() {
  if (process.env.DRAFTS_PASSPHRASE) return Promise.resolve(process.env.DRAFTS_PASSPHRASE);
  return new Promise((resolve) => {
    const rl = readline.createInterface({ input: process.stdin, output: process.stdout, terminal: true });
    let prompted = false;
    // Mute echoed characters, but still show the prompt and the final newline.
    rl._writeToOutput = (chunk) => {
      if (!prompted) { process.stdout.write(chunk); prompted = true; return; }
      if (/\r?\n/.test(chunk)) process.stdout.write(chunk);
    };
    rl.question('Passphrase: ', (answer) => { rl.close(); process.stdout.write('\n'); resolve(answer); });
    rl.on('SIGINT', () => { process.stdout.write('\n'); process.exit(1); });
  });
}

async function encrypt(plaintext, passphrase) {
  const enc = new TextEncoder();
  const salt = webcrypto.getRandomValues(new Uint8Array(SALT_LEN));
  const iv = webcrypto.getRandomValues(new Uint8Array(IV_LEN));
  const baseKey = await subtle.importKey('raw', enc.encode(passphrase), 'PBKDF2', false, ['deriveKey']);
  const aesKey = await subtle.deriveKey(
    { name: 'PBKDF2', salt, iterations: ITERATIONS, hash: 'SHA-256' },
    baseKey,
    { name: 'AES-GCM', length: 256 },
    false,
    ['encrypt'],
  );
  const ctBuf = await subtle.encrypt({ name: 'AES-GCM', iv }, aesKey, enc.encode(plaintext));
  return { salt: toB64(salt), iv: toB64(iv), ct: toB64(new Uint8Array(ctBuf)), iters: ITERATIONS };
}

async function main() {
  if (!fs.existsSync(PLAINTEXT_PATH)) {
    console.error(`Plaintext file not found: ${PLAINTEXT_PATH}`);
    console.error('Create it (it is gitignored) with your under-submission paper list, then re-run.');
    process.exit(1);
  }
  const plaintext = fs.readFileSync(PLAINTEXT_PATH, 'utf8');
  const passphrase = await readPassphrase();
  if (!passphrase) { console.error('Empty passphrase — aborting.'); process.exit(1); }

  const data = await encrypt(plaintext, passphrase);
  fs.mkdirSync(path.dirname(OUTPUT_PATH), { recursive: true });
  const out =
    '// AUTO-GENERATED by src/encrypt-drafts.mjs — do not edit by hand.\n' +
    '// Encrypted "under submission" papers. Decrypt in the browser at #drafts with the passphrase.\n' +
    '// Plaintext lives in resources/drafts.private.html (gitignored, never committed).\n' +
    'window.__PRIVATE_DRAFTS__ = ' + JSON.stringify(data, null, 2) + ';\n';
  fs.writeFileSync(OUTPUT_PATH, out);
  console.log(`Encrypted ${Buffer.byteLength(plaintext)} bytes -> ${OUTPUT_PATH}`);
  console.log('Reload the site and visit /#drafts to verify.');
}

main().catch((e) => { console.error(e); process.exit(1); });
